### PR TITLE
Fix / clarification for #53

### PR DESCRIPTION
**Pull request by mrdavey**

### CODE REVIEW

**Comment by pixelmatrix** [comment]
@mrdavey Do you think ropsten is really the best default? I feel like it mainnet would be more predictable.

**Comment by pixelmatrix** [comment]
I agree with that @Ybrin. With a default value it will always be confusing to someone sending on a different chain. Without the context of an instance of web3 or a provider it's impossible to know what network the user intends to sign for, although in production it will almost always be mainnet.

I think the best course of action here would be dropping the default value so that it's more clear to the caller.

**Comment by Ybrin** [comment]
Thanks @pixelmatrix 

@mrdavey Do you want to implement those changes in your pull request?

**Comment by rogerluan** [comment]
I agree, having no default value would be better so the user has to decide which one he'd like to use, explicitly.

Something that I'd implement, though, is type safety when doing sending that parameter. I implemented an enum like:

```
enum Chain : Int {
    typealias RawValue = Int

    case olympic = 0
    case ethereumMain = 1
    case ethereumClassic = 61 // Former 1
    case expanse = 2 // Former 1
    // case morden = 2 // Deprecated: public Ethereum testnet, now Ethereum Classic testnet
    case ropsten = 3
    case rinkeby = 4
    case ubiq = 8
    case kovan = 42
    case sokol = 77
    case core = 99
    case musicoin = 7762959
    case aquachain = 61717561
}
```

And there could be an overload that takes either such enum, or a raw value (e.g. `Int` or `EthereumQuantity`), so that the user can use the type safe implementation, or a raw value if none of those values fit (for a future-proof implementation).

Thoughts @mrdavey @Ybrin  @pixelmatrix ?

**Comment by pixelmatrix** [comment]
I like the idea of creating a type for the chains, along with an overload that takes Int for compatibility with future chains. 

In Bitski's SDK we've made our own "Network" enum for other reasons, but we could easily adapt something like this if it were part of the core Web3 library.

**Comment by Ybrin** [comment]
Yes, type safety for the chain id would be perfect. I would extend the enum to have a function like the following:

```

**Comment by Ybrin** [comment]
Then we could either call it like that for supported networks:

```Swift
tx.sign(with: myKey, chain: . ropsten)
```

Or for custom chain ids like the following:

```Swift
tx.sign(with: myKey, chain: . custom(133))
```

**Comment by rogerluan** [comment]
Sure, I'll open a separate PR, if you don't mind.

**Comment by rogerluan** [comment]
And here it is: https://github.com/Boilertalk/Web3.swift/pull/62

**Comment by mrdavey** [comment]
Great discussion and thanks @rogerluan for creating the PR!

**Comment by rogerluan** [comment]
Due to our discussions and the creation of https://github.com/Boilertalk/Web3.swift/pull/62, I think this PR can be closed, right @mrdavey ?

**Comment by mrdavey** [comment]
Yes thanks for the reminder! I'll close it now.

**Pull request closed without merging**
